language: node_js
node_js:
- stable
install: npm install
services:
- mongodb
script: npm test
after_success: npm run coverage
deploy:
  provider: heroku
  api_key:
    secure: IutHRHUdMf/qB7gnMLmv6ZVyhRSoXgECoNvPOTi40cjytcvqMrRdHre14fN0XNkm9qAN3mwaYmihlHtKpXPPesHOePJo8ETyLVbD7VmgLDPg2mEHxnSmw2I7PRx7bIK7BESg4+VNsrY/rsm5xHijIAhvTrlCVEManqW2yNMHUjdXJSHn63uRaBzARzrjc0HJ/h62h7mrEZ65QZjIEqE1EW7cFY0xeFz1XObXun1CPJ1KIwdU4FFZZK+injSiKTLXY75P+3sxcM3rqtjRWEnz8JyznIPsutQrvYlHqTzCdXcergMh6OuAeE+oxQ+dBmGB8N+0An0FuPNyPlay+8uqj7gtqKNw+aJeoQehekKIzopWXTZspJK5qNBLhgald+W7nVKbYvq4JgWBTSnXEBTlLSvJ/zGYtuv2BOilCOFiI4YeZBGpvN8GvmJAJ1SjG+Po/omX5TY5axut4cJtC9qlVUsFNzrJbsEx3kGy+BPrdQRM99H8P5qaNskOAcMusxuZS4Jn1WSCMQdqnWhuWvKYiGo6NjEaN+Yiwngcwi79pkpRdlgbXg771kncsOdaH9z9wfKgZ69uApv6d9S/PCMiSUHjhV+s3dfmk2eNQvf9Wr7C2gLwuOE2/Ngu/HNbHhDXVMP8PlFPQEVVtLZIrhk04EeKFdBgf3N0IWJk7pFIPcA=
  app: travis-coveralls-ci-test-app
  on:
    repo: marymacmurray/mongodb-mongoose-express-ci
  run:
    - "node seed/userProjects.js"
