language: node_js
node_js:
- stable
install: npm install
services:
- mongodb
script: npm test
after_success: npm run coverage
deploy:
  provider: heroku
  api_key:
    secure: LgFnPMxKSnBpnICJf0huZeq/mvrg4ClQ2nKax+sQ1ir/DjNnLER1SSaHUu5GKUc6PNBAjcGdphna38+nSfVfq6sIxUpMsCa7Gd8C816iekGNwpPWyPVFqf/DGVU2WQfAlx8TyoLvasNg0jGHDMrvKvTKuzaeutWZ22cnDZXswjSEbXahtkW3gZpEGzysA17AMq34lc7Z3cHlUVLN79SC6/CUmBaRSZa7K/MgVnn0w1NpWB/k2/zeuDIXoLwo5coOjgcA5GhABHQLuMW2gP0LubbdcIVtKRgbMsUNTA7KP+QP/v9EqBcec1Sgt0NrqXfOyT9D5WSkLUmgZGhiWOzBTbHSLcSEmDSPCJCSe7rOEt/PQpTMYvD5USwuSlZgYiqLAYdshgF6pwzYYMSeAeEZRWSsJvj85qN8rAutsQRD9wpDgDfMxgKbEq2Eab3Wpn8CtNbV+JVV5pq2LyoqvAaPqowpzIZTTecXWaD4exOAEGnZYl/c3OxeRVvxkoJeEEO1pvZjjvfKdB1Pq1kjmk344h71hpMV16Bnn3NsrCj3OOzaJxKmrMEWxTeTESgOVVhN6VahYcjVOI92+fhlDqLBivKKEUJMae6vjTZdNi+6Z5+OO9+Q1uPHrJ1k93WQwO2I4FeWZAxRmrWutuOA/axmTG4/0my4bqbLDxy0YrjdRq4=
  app: travis-coveralls-ci-test-app
  on:
    repo: marymacmurray/mongodb-mongoose-express-ci
  run:
    - "node seed/userProjects.js"
